### ISSUE TITLE
Add support of r

### ISSUE THREAD

**Issue by damn-war** [dariusgm/lunarvim#3]
"i" want to use this container as my ide for r development:

r cli
r linter
r autocompletion
r formatter

**Comment by dariusgm** [comment]
I just pushed a version that allows R execution. Also added an r.languageserver package via Mason. I also added a test for R and Rscript. Can you give it a try if it fits your needs and provide some feedback? For linter and autocomplete you may come up with a idea what fits your needs best, as I have no knowledge about R.

**Comment by damn-war** [comment]
Great, thanks a lot.
will have a look and give you feedback. :)
